name: "Demo: Advanced Usage"

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '12 6 3 */2 *'

jobs:
  irulescan-action:
    runs-on: ubuntu-latest
    name: "Workflow"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run irulescan-action
        uses: simonkowallik/irulescan-action@v3
        id: my_irulescan_action_id

      - name: Save irulescan output to file
        run: |
          cat << 'EOF' > irulescan_result.json
          ${{ steps.my_irulescan_action_id.outputs.result }}
          EOF

      - name: "Do whatever you need to do with the output file"
        run: |
          cat irulescan_result.json

      - name: "Example 1: json2yaml"
        uses: mikefarah/yq@master
        with:
          cmd: yq -p=json -o=yaml irulescan_result.json

      - name: "Example 2: json2yaml : Print result"
        run: echo "${{ steps.json2yaml.outputs.output }}"
