name: "Demo: Custom CMD"

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '12 6 3 */2 *'

jobs:
  irulescan-action:
    runs-on: ubuntu-latest
    name: "Workflow"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run irulescan-action with custom docker CMD
        uses: simonkowallik/irulescan-action@v3
        with:
          cmd: irulescan check example/irules/wrong_extension.txt
