name: "Functional Tests"

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '12 6 3 */2 *'

jobs:
  irulescan-action:
    runs-on: ubuntu-latest
    name: "Workflow"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run irulescan-action
        uses: simonkowallik/irulescan-action@main
        id: my_irulescan_action_id

      - name: Save irulescan output to file
        run: |
          cat << 'EOF' > irulescan_result.json
          ${{ steps.my_irulescan_action_id.outputs.result }}
          EOF

      - name: Convert json to yaml using yq
        uses: mikefarah/yq@master
        with:
          cmd: yq -p=json -o=yaml irulescan_result.json

      - name: Run irulescan-action with custom docker CMD
        uses: simonkowallik/irulescan-action@main
        id: irulescan_action_custom_cmd
        with:
          cmd: irulescan check example/irules/non_default_extension.txt

      - name: Check custom docker CMD output
        run: |
          cat << 'EOF' > irulescan_output.txt
          ${{ steps.irulescan_action_custom_cmd.outputs.result }}
          EOF
          grep -i 'warning' irulescan_output.txt
